/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.BorderLayout;
import java.awt.Color;

/**
 *
 * @author user
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton6 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        lab = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        home_btn = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        doctor_btn = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        nurse_btn = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        emp_btn = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        patient_btn = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        department_btn = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        lab1 = new javax.swing.JLabel();
        homePanel = new javax.swing.JPanel();

        jButton6.setBackground(new java.awt.Color(14, 1, 54));
        jButton6.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        jButton6.setForeground(new java.awt.Color(14, 1, 54));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/007-hospital-bed.png"))); // NOI18N
        jButton6.setText("Patient");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(14, 1, 54));

        jPanel1.setBackground(new java.awt.Color(14, 1, 54));
        jPanel1.setPreferredSize(new java.awt.Dimension(1350, 700));

        jPanel2.setBackground(new java.awt.Color(173, 170, 181));
        jPanel2.setPreferredSize(new java.awt.Dimension(1350, 100));

        jLabel1.setForeground(new java.awt.Color(255, 204, 204));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/008-hospital-symbol.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        jPanel8.setBackground(new java.awt.Color(14, 1, 54));

        lab.setBackground(new java.awt.Color(14, 1, 54));
        lab.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        lab.setForeground(new java.awt.Color(14, 1, 54));
        lab.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/005-test-tubes.png"))); // NOI18N
        lab.setText("Laboratory");
        lab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                labActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(14, 1, 54));

        home_btn.setBackground(new java.awt.Color(204, 255, 102));
        home_btn.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        home_btn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        home_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/001-eye-closeup.png"))); // NOI18N
        home_btn.setText(" HOME");
        home_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                home_btnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                home_btnMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                home_btnMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(home_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(home_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel4.setBackground(new java.awt.Color(14, 1, 54));

        doctor_btn.setBackground(new java.awt.Color(14, 1, 54));
        doctor_btn.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        doctor_btn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        doctor_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/006-phonendoscope.png"))); // NOI18N
        doctor_btn.setText("DOCTOR");
        doctor_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                doctor_btnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                doctor_btnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                doctor_btnMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(doctor_btn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(doctor_btn, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel5.setBackground(new java.awt.Color(14, 1, 54));

        nurse_btn.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        nurse_btn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nurse_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/002-nurse-silhouette.png"))); // NOI18N
        nurse_btn.setText("NURSE");
        nurse_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nurse_btnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                nurse_btnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                nurse_btnMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(nurse_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(nurse_btn, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
        );

        jPanel6.setBackground(new java.awt.Color(14, 1, 54));

        emp_btn.setBackground(new java.awt.Color(14, 1, 54));
        emp_btn.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        emp_btn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        emp_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/003-health-thermometer.png"))); // NOI18N
        emp_btn.setText("STAFF");
        emp_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                emp_btnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                emp_btnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                emp_btnMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(emp_btn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(emp_btn, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
        );

        jPanel7.setBackground(new java.awt.Color(14, 1, 54));

        patient_btn.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        patient_btn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        patient_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/007-hospital-bed.png"))); // NOI18N
        patient_btn.setText("PATIENT");
        patient_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                patient_btnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                patient_btnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                patient_btnMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(patient_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(patient_btn, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel9.setBackground(new java.awt.Color(14, 1, 54));

        department_btn.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        department_btn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        department_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/004-drop-with-hospital-symbol.png"))); // NOI18N
        department_btn.setText("WARD");
        department_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                department_btnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                department_btnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                department_btnMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(department_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(department_btn, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
        );

        jPanel10.setBackground(new java.awt.Color(14, 1, 54));

        lab1.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        lab1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lab1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/005-test-tubes.png"))); // NOI18N
        lab1.setText("LABORATORY");
        lab1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lab1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lab1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lab1MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lab1, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lab1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(195, 195, 195)
                .addComponent(lab, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        homePanel.setBackground(new java.awt.Color(173, 170, 181));

        javax.swing.GroupLayout homePanelLayout = new javax.swing.GroupLayout(homePanel);
        homePanel.setLayout(homePanelLayout);
        homePanelLayout.setHorizontalGroup(
            homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1154, Short.MAX_VALUE)
        );
        homePanelLayout.setVerticalGroup(
            homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 601, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(homePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1366, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(homePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1366, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 722, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void nurse_btnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nurse_btnMouseExited
        jPanel5.setBackground(new java.awt.Color(14, 1, 54));
    }//GEN-LAST:event_nurse_btnMouseExited

    private void nurse_btnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nurse_btnMouseEntered
        jPanel5.setBackground(new java.awt.Color(173,170,181));
    }//GEN-LAST:event_nurse_btnMouseEntered

    private void nurse_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nurse_btnMouseClicked
        Nurse nurse = new Nurse();
        nurse.setVisible(true);
        homePanel.setLayout(new BorderLayout());
        homePanel.removeAll();

        homePanel.add(nurse);
        homePanel.validate();
        homePanel.repaint();
    }//GEN-LAST:event_nurse_btnMouseClicked

    private void doctor_btnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_doctor_btnMouseExited
        jPanel4.setBackground(new java.awt.Color(14, 1, 54));
    }//GEN-LAST:event_doctor_btnMouseExited

    private void doctor_btnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_doctor_btnMouseEntered
        jPanel4.setBackground(new java.awt.Color(173,170,181));
    }//GEN-LAST:event_doctor_btnMouseEntered

    private void doctor_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_doctor_btnMouseClicked
        jPanel4.setBackground(new java.awt.Color(173,170,181));
        Doctor doctor = new Doctor();
        doctor.setVisible(true);
        homePanel.setLayout(new BorderLayout());
        homePanel.removeAll();;

        homePanel.add(doctor);
        homePanel.validate();
        homePanel.repaint();
    }//GEN-LAST:event_doctor_btnMouseClicked

    private void home_btnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_home_btnMousePressed

    }//GEN-LAST:event_home_btnMousePressed

    private void home_btnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_home_btnMouseExited
        jPanel3.setBackground(new java.awt.Color(14, 1, 54));
    }//GEN-LAST:event_home_btnMouseExited

    private void home_btnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_home_btnMouseEntered
        jPanel3.setBackground(new java.awt.Color(173,170,181));
    }//GEN-LAST:event_home_btnMouseEntered

    private void labActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_labActionPerformed
        treatment tr = new treatment();
        tr.setVisible(true);
        homePanel.setLayout(new BorderLayout());
        homePanel.removeAll();

        homePanel.add(tr);
        homePanel.validate();
        homePanel.repaint();
    }//GEN-LAST:event_labActionPerformed

    private void emp_btnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emp_btnMouseExited
        jPanel6.setBackground(new java.awt.Color(14, 1, 54));
    }//GEN-LAST:event_emp_btnMouseExited

    private void emp_btnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emp_btnMouseEntered
        jPanel6.setBackground(new java.awt.Color(173,170,181));
    }//GEN-LAST:event_emp_btnMouseEntered

    private void emp_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emp_btnMouseClicked
        otherEmployee emp = new otherEmployee();
        emp.setVisible(true);
        homePanel.setLayout(new BorderLayout());
        homePanel.removeAll();;

        homePanel.add(emp);
        homePanel.validate();
        homePanel.repaint();
    }//GEN-LAST:event_emp_btnMouseClicked

    private void patient_btnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_patient_btnMouseEntered
        jPanel7.setBackground(new java.awt.Color(173,170,181));
    }//GEN-LAST:event_patient_btnMouseEntered

    private void patient_btnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_patient_btnMouseExited
        jPanel7.setBackground(new java.awt.Color(14, 1, 54));
    }//GEN-LAST:event_patient_btnMouseExited

    private void patient_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_patient_btnMouseClicked
       Patient patient = new Patient();
        patient.setVisible(true);
        homePanel.setLayout(new BorderLayout());
        homePanel.removeAll();;

        homePanel.add(patient);
        homePanel.validate();
        homePanel.repaint();
    }//GEN-LAST:event_patient_btnMouseClicked

    private void department_btnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_department_btnMouseExited
         jPanel9.setBackground(new java.awt.Color(14, 1, 54));
    }//GEN-LAST:event_department_btnMouseExited

    private void department_btnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_department_btnMouseEntered
        jPanel9.setBackground(new java.awt.Color(173,170,181));
    }//GEN-LAST:event_department_btnMouseEntered

    private void department_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_department_btnMouseClicked
         wards section = new wards();
        section.setVisible(true);
        homePanel.setLayout(new BorderLayout());
        homePanel.removeAll();;

        homePanel.add(section);
        homePanel.validate();
        homePanel.repaint();
    }//GEN-LAST:event_department_btnMouseClicked

    private void lab1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lab1MouseClicked
        treatment tr = new treatment();
        tr.setVisible(true);
        homePanel.setLayout(new BorderLayout());
        homePanel.removeAll();

        homePanel.add(tr);
        homePanel.validate();
        homePanel.repaint();
    }//GEN-LAST:event_lab1MouseClicked

    private void lab1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lab1MouseExited
        jPanel10.setBackground(new java.awt.Color(14, 1, 54));
    }//GEN-LAST:event_lab1MouseExited

    private void lab1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lab1MouseEntered
        jPanel10.setBackground(new java.awt.Color(173,170,181));
    }//GEN-LAST:event_lab1MouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel department_btn;
    private javax.swing.JLabel doctor_btn;
    private javax.swing.JLabel emp_btn;
    private javax.swing.JPanel homePanel;
    private javax.swing.JLabel home_btn;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JButton lab;
    private javax.swing.JLabel lab1;
    private javax.swing.JLabel lab2;
    private javax.swing.JLabel nurse_btn;
    private javax.swing.JLabel patient_btn;
    // End of variables declaration//GEN-END:variables
}
